apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: icam-demo
  name: bookinfo-subscription
  namespace: bookinfo-project
spec:
  channel: bookinfo-entitlement/bookinfo-channel
  source: https://raw.githubusercontent.com/dymaczew/charts/master/repo/incubator/ 
  name: bookinfo
  packageFilter:
    version: 1.0.7
  placement:
    placementRef:
      name: demo-placementrule
      kind: PlacementRule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: bookinfo
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo
    - path: spec.values
      value: |
        ingress:
          host: bookinfo.apps.blue-12.dev.multicloudops.io
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo-app
  namespace: bookinfo-project
spec:
  selector:
    matchExpressions:
    - key: purpose
      operator: In
      values:
      - icam-demo
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: dev-placementrule
  namespace: bookinfo-project
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Dev
  clusterReplicas: 1
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: production-placementrule
  namespace: bookinfo-project
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Production
  clusterReplicas: 1
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: demo-placementrule
  namespace: bookinfo-project
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Demo
  clusterReplicas: 1

